In [0]:
import numpy as np
print(np.__version__)

1.14.2


# Numpy 

## Numpy Array

In [0]:
x = np.array([1,2,3])
print(x.__class__)
print(x.shape)


<class 'numpy.ndarray'>
(3,)
1


In [0]:
print(x.ndim)

In [0]:
W = np.array([[1,2,3], [4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


## ELement-wise Calculation

In [0]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])

In [0]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [0]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

## Broadcast

In [0]:
A = np.array([[1,2],[3,4]])
print(A * 10)

[[10 20]
 [30 40]]


In [0]:
b = np.array([10,20])
print(A * b)

[[10 40]
 [30 80]]


## Inner Product

In [0]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


## Matrix Multiply

In [0]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]
